//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller2ServiciosWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBpesajeEntities : DbContext
    {
        public DBpesajeEntities()
            : base("name=DBpesajeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Camion> Camions { get; set; }
        public virtual DbSet<FotoPesaje> FotoPesajes { get; set; }
        public virtual DbSet<Pesaje> Pesajes { get; set; }
    }
}
