//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller2ServiciosWeb.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Pesaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pesaje()
        {
            this.FotoPesajes = new HashSet<FotoPesaje>();
        }
    
        public int id { get; set; }
        public System.DateTime FechaPesaje { get; set; }
        public string PlacaCamion { get; set; }
        public float Peso { get; set; }
        public string Estacion { get; set; }
        [JsonIgnore]
        public virtual Camion Camion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<FotoPesaje> FotoPesajes { get; set; }
    }
}
